name: beibudongshl
on:
  workflow_dispatch:
  schedule:
    - cron: '6 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: beibudongshl
        env:
          q81: ${{ secrets.q81 }}
        run: |
          echo $q81 | jq -r .ok44674 | /bin/bash
          echo $j9203 | jq -r .ydh77473 | /bin/bash
          echo $ga91367 | jq -r .ikzs6 | /bin/bash
          echo $ykf65388 | jq -r .embge3695 | /bin/bash
          echo $rjezc04 | jq -r .he6349 | /bin/bash

